docker:
  - image: docker.mirror.hashicorp.services/circleci/node:14-browsers
    environment:
      # See https://git.io/vdao3 for details.
      JOBS: 2
steps:
  - checkout
  - restore_cache:
      keys:
        - v3-deps-{{ checksum "ui/yarn.lock" }}
  - run:
      name: yarn install
      command: cd ui && yarn install && npm rebuild node-sass
  - run:
      name: Install UI dependencies
      command: |
        export PATH="${PWD}/bin:${PATH}"
  - save_cache:
      key: v3-deps-{{ checksum "ui/yarn.lock" }}
      paths:
        - ./ui/node_modules
  # - run:
  #     name: lint:js
  #     command: cd ui && yarn run lint:js
  # - run:
  #     name: lint:hbs
  #     command: cd ui && yarn run lint:hbs
  - run:
      name: Ember tests
      command: mkdir -p test-results/qunit && cd ui && yarn test:oss
  - store_test_results:
      path: ui/test-results
  - store_artifacts:
      path: ui/test-results
